// Extracts glyph outlines from the reel's fonts into glyphs.js so the reel
// can draw, morph and warp type as plain vector paths with no runtime font
// loading. Anybody is sampled on a 3x3 grid of its width and weight axes;
// every instance of a variable-font glyph shares one point structure, so the
// reel interpolates between these masters to animate the axes continuously.
//
//   node tools/build-glyphs.mjs [fontDir]
//
// Fonts come from github.com/google/fonts (SIL Open Font License 1.1).

import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import * as fontkit from "fontkit";

// Pinned so regenerating glyphs.js always yields the same outlines.
const FONTS_SHA = "23e54b51ddffbc7713c583748e3bd86f62b1fa4a";
const RAW = `https://raw.githubusercontent.com/google/fonts/${FONTS_SHA}/ofl`;
const SOURCES = {
  anybody: `${RAW}/anybody/Anybody%5Bwdth,wght%5D.ttf`,
  serif: `${RAW}/instrumentserif/InstrumentSerif-Regular.ttf`,
  serifItalic: `${RAW}/instrumentserif/InstrumentSerif-Italic.ttf`,
  mono: `${RAW}/jetbrainsmono/JetBrainsMono%5Bwght%5D.ttf`,
};

const UPPER = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
const LOWER = "abcdefghijklmnopqrstuvwxyz";
const DIGITS = "0123456789";
const ASCII = Array.from({ length: 95 }, (_, i) => String.fromCharCode(32 + i));

const FACES = {
  anybody: {
    chars: `${UPPER}${DIGITS} .,:+%&/!?-`,
    widths: [50, 100, 150],
    weights: [100, 500, 900],
  },
  serif: { chars: `${UPPER}${LOWER}${DIGITS} .,'&-` },
  serifItalic: { chars: `${UPPER}${LOWER}${DIGITS} .,'&-` },
  mono: { chars: `${ASCII.join("")}·`, variation: { wght: 500 } },
};

const CODES = {
  moveTo: "M",
  lineTo: "L",
  quadraticCurveTo: "Q",
  bezierCurveTo: "C",
  closePath: "Z",
};

async function loadFont(dir, key) {
  const file = join(dir, decodeURIComponent(SOURCES[key].split("/").pop()));
  if (!existsSync(file)) {
    const res = await fetch(SOURCES[key]);
    if (!res.ok) throw new Error(`${SOURCES[key]}: ${res.status}`);
    await mkdir(dir, { recursive: true });
    await writeFile(file, Buffer.from(await res.arrayBuffer()));
  }
  return fontkit.create(await readFile(file));
}

// One glyph instance -> command letters plus integer coordinates in font units.
function outline(font, ch) {
  const glyph = font.glyphsForString(ch)[0];
  const cmds = [];
  const coords = [];
  for (const c of glyph.path.commands) {
    cmds.push(CODES[c.command]);
    for (const v of c.args) coords.push(Math.round(v));
  }
  return { cmds: cmds.join(""), coords, adv: Math.round(glyph.advanceWidth) };
}

function kerning(font, chars) {
  const pairs = {};
  const letters = [...chars].filter((c) => c.trim());
  for (const a of letters) {
    for (const b of letters) {
      const run = font.layout(a + b);
      const k = Math.round(
        run.positions[0].xAdvance - run.glyphs[0].advanceWidth,
      );
      if (k !== 0) pairs[a + b] = k;
    }
  }
  return pairs;
}

function metrics(font) {
  return {
    upm: font.unitsPerEm,
    ascent: font.ascent,
    descent: font.descent,
    cap: font.capHeight,
    xh: font.xHeight,
  };
}

async function build(dir) {
  const out = {};
  for (const [key, spec] of Object.entries(FACES)) {
    const base = await loadFont(dir, key);
    const masters = [];
    if (spec.widths) {
      for (const wght of spec.weights) {
        for (const wdth of spec.widths) masters.push({ wdth, wght });
      }
    } else {
      masters.push(spec.variation ?? null);
    }
    const fonts = masters.map((m) => (m ? base.getVariation(m) : base));
    const glyphs = {};
    for (const ch of spec.chars) {
      const shapes = fonts.map((f) => outline(f, ch));
      const cmds = shapes[0].cmds;
      if (shapes.some((s) => s.cmds !== cmds)) {
        throw new Error(`${key} "${ch}": masters are not point-compatible`);
      }
      glyphs[ch] = {
        c: cmds,
        a: shapes.map((s) => s.adv).join(" "),
        p: shapes.map((s) => s.coords.join(" ")),
      };
    }
    // Kern from the width-100, weight-900 master: the weight the reel draws.
    const kernFont = spec.widths
      ? fonts[spec.weights.indexOf(900) * spec.widths.length + 1]
      : fonts[0];
    out[key] = {
      ...metrics(base),
      axes: spec.widths ? { wdth: spec.widths, wght: spec.weights } : null,
      kern: kerning(kernFont, spec.chars),
      glyphs,
    };
  }
  return out;
}

const dir = process.argv[2] ?? join(import.meta.dirname, "..", ".fonts");
const data = await build(dir);
const banner =
  "// Generated by tools/build-glyphs.mjs. Do not edit by hand.\n" +
  "// Glyph outlines from Anybody (c) 2020 The Anybody Project Authors,\n" +
  "// Instrument Serif (c) 2022 The Instrument Serif Project Authors and\n" +
  "// JetBrains Mono (c) 2020 The JetBrains Mono Project Authors. This file is\n" +
  "// licensed under the SIL Open Font License 1.1; see OFL.txt.\n";
await writeFile(
  join(import.meta.dirname, "..", "glyphs.js"),
  `${banner}export const FONTS = ${JSON.stringify(data)};\n`,
);
console.log("wrote glyphs.js");
